DROP SCHEMA IF EXISTS SCHEMAA;

CREATE SCHEMA SCHEMAA;

CREATE TABLE IF NOT EXISTS SCHEMAA.SALA
(
	ID INTEGER NOT NULL,
	NUMERO VARCHAR(20) NOT NULL,
	CAPACIDADE INTEGER NULL,
	PAVILHAO_ID INTEGER NULL,
	TIPO_SALA_ID INTEGER NULL,
	CONSTRAINT PKSALA PRIMARY KEY (ID)
);
